/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Document Management System API
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@dms.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AuditLogPageResponse } from '../models';
/**
 * AuditApi - axios parameter creator
 */
export const AuditApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary File activity history
         * @param {string} [fileId] 
         * @param {string} [folderId] 
         * @param {string} [userId] 
         * @param {GetFileActivityActionEnum} [action] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort expression: field,asc or field,desc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFileActivity: async (fileId?: string, folderId?: string, userId?: string, action?: GetFileActivityActionEnum, from?: string, to?: string, page?: number, size?: number, sort?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/audit/file-activity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (fileId !== undefined) {
                localVarQueryParameter['fileId'] = fileId;
            }

            if (folderId !== undefined) {
                localVarQueryParameter['folderId'] = folderId;
            }

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }

            if (action !== undefined) {
                localVarQueryParameter['action'] = action;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Security audit trail
         * @param {string} [userId] 
         * @param {GetSecurityAuditEventTypeEnum} [eventType] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSecurityAudit: async (userId?: string, eventType?: GetSecurityAuditEventTypeEnum, from?: string, to?: string, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/audit/security`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }

            if (eventType !== undefined) {
                localVarQueryParameter['eventType'] = eventType;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary User activity logs
         * @param {string} [userId] 
         * @param {string} [action] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserActivity: async (userId?: string, action?: string, from?: string, to?: string, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/audit/user-activity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }

            if (action !== undefined) {
                localVarQueryParameter['action'] = action;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuditApi - functional programming interface
 */
export const AuditApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuditApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary File activity history
         * @param {string} [fileId] 
         * @param {string} [folderId] 
         * @param {string} [userId] 
         * @param {GetFileActivityActionEnum} [action] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort expression: field,asc or field,desc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFileActivity(fileId?: string, folderId?: string, userId?: string, action?: GetFileActivityActionEnum, from?: string, to?: string, page?: number, size?: number, sort?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuditLogPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFileActivity(fileId, folderId, userId, action, from, to, page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuditApi.getFileActivity']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Security audit trail
         * @param {string} [userId] 
         * @param {GetSecurityAuditEventTypeEnum} [eventType] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSecurityAudit(userId?: string, eventType?: GetSecurityAuditEventTypeEnum, from?: string, to?: string, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuditLogPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSecurityAudit(userId, eventType, from, to, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuditApi.getSecurityAudit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary User activity logs
         * @param {string} [userId] 
         * @param {string} [action] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserActivity(userId?: string, action?: string, from?: string, to?: string, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuditLogPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserActivity(userId, action, from, to, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuditApi.getUserActivity']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuditApi - factory interface
 */
export const AuditApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuditApiFp(configuration)
    return {
        /**
         * 
         * @summary File activity history
         * @param {string} [fileId] 
         * @param {string} [folderId] 
         * @param {string} [userId] 
         * @param {GetFileActivityActionEnum} [action] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort expression: field,asc or field,desc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFileActivity(fileId?: string, folderId?: string, userId?: string, action?: GetFileActivityActionEnum, from?: string, to?: string, page?: number, size?: number, sort?: string, options?: RawAxiosRequestConfig): AxiosPromise<AuditLogPageResponse> {
            return localVarFp.getFileActivity(fileId, folderId, userId, action, from, to, page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Security audit trail
         * @param {string} [userId] 
         * @param {GetSecurityAuditEventTypeEnum} [eventType] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSecurityAudit(userId?: string, eventType?: GetSecurityAuditEventTypeEnum, from?: string, to?: string, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<AuditLogPageResponse> {
            return localVarFp.getSecurityAudit(userId, eventType, from, to, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary User activity logs
         * @param {string} [userId] 
         * @param {string} [action] 
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserActivity(userId?: string, action?: string, from?: string, to?: string, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<AuditLogPageResponse> {
            return localVarFp.getUserActivity(userId, action, from, to, page, size, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuditApi - object-oriented interface
 */
export class AuditApi extends BaseAPI {
    /**
     * 
     * @summary File activity history
     * @param {string} [fileId] 
     * @param {string} [folderId] 
     * @param {string} [userId] 
     * @param {GetFileActivityActionEnum} [action] 
     * @param {string} [from] 
     * @param {string} [to] 
     * @param {number} [page] Zero-based page index
     * @param {number} [size] Number of items per page
     * @param {string} [sort] Sort expression: field,asc or field,desc
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getFileActivity(fileId?: string, folderId?: string, userId?: string, action?: GetFileActivityActionEnum, from?: string, to?: string, page?: number, size?: number, sort?: string, options?: RawAxiosRequestConfig) {
        return AuditApiFp(this.configuration).getFileActivity(fileId, folderId, userId, action, from, to, page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Security audit trail
     * @param {string} [userId] 
     * @param {GetSecurityAuditEventTypeEnum} [eventType] 
     * @param {string} [from] 
     * @param {string} [to] 
     * @param {number} [page] Zero-based page index
     * @param {number} [size] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSecurityAudit(userId?: string, eventType?: GetSecurityAuditEventTypeEnum, from?: string, to?: string, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return AuditApiFp(this.configuration).getSecurityAudit(userId, eventType, from, to, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary User activity logs
     * @param {string} [userId] 
     * @param {string} [action] 
     * @param {string} [from] 
     * @param {string} [to] 
     * @param {number} [page] Zero-based page index
     * @param {number} [size] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUserActivity(userId?: string, action?: string, from?: string, to?: string, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return AuditApiFp(this.configuration).getUserActivity(userId, action, from, to, page, size, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetFileActivityActionEnum = {
    Upload: 'upload',
    Download: 'download',
    View: 'view',
    Move: 'move',
    Copy: 'copy',
    Delete: 'delete',
    Restore: 'restore',
    Share: 'share',
    Rename: 'rename',
    Version: 'version'
} as const;
export type GetFileActivityActionEnum = typeof GetFileActivityActionEnum[keyof typeof GetFileActivityActionEnum];
export const GetSecurityAuditEventTypeEnum = {
    Login: 'login',
    Logout: 'logout',
    LoginFailed: 'login_failed',
    PasswordChange: 'password_change',
    RoleChange: 'role_change',
    PermissionChange: 'permission_change',
    MfaEnabled: 'mfa_enabled',
    MfaDisabled: 'mfa_disabled'
} as const;
export type GetSecurityAuditEventTypeEnum = typeof GetSecurityAuditEventTypeEnum[keyof typeof GetSecurityAuditEventTypeEnum];
