/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Document Management System API
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@dms.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BreadcrumbResponse } from '../models';
// @ts-ignore
import type { DirectoryResponse } from '../models';
// @ts-ignore
import type { SearchResultPageResponse } from '../models';
/**
 * ExplorerApi - axios parameter creator
 */
export const ExplorerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get breadcrumb path for a folder
         * @param {string} folderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBreadcrumb: async (folderId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'folderId' is not null or undefined
            assertParamExists('getBreadcrumb', 'folderId', folderId)
            const localVarPath = `/explorer/breadcrumb`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (folderId !== undefined) {
                localVarQueryParameter['folderId'] = folderId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List directory contents
         * @param {string} [folderId] Folder to list; omit for root
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort expression: field,asc or field,desc
         * @param {ListDirectoryTypeEnum} [type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDirectory: async (folderId?: string, page?: number, size?: number, sort?: string, type?: ListDirectoryTypeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/explorer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (folderId !== undefined) {
                localVarQueryParameter['folderId'] = folderId;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search files and folders
         * @param {string} [q] Full-text search query
         * @param {SearchTypeEnum} [type] 
         * @param {string} [mimeType] 
         * @param {string} [ownerId] 
         * @param {Array<string>} [tags] 
         * @param {string} [createdFrom] 
         * @param {string} [createdTo] 
         * @param {string} [modifiedFrom] 
         * @param {string} [modifiedTo] 
         * @param {string} [folderId] Scope search to a specific folder (and descendants)
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort expression: field,asc or field,desc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search: async (q?: string, type?: SearchTypeEnum, mimeType?: string, ownerId?: string, tags?: Array<string>, createdFrom?: string, createdTo?: string, modifiedFrom?: string, modifiedTo?: string, folderId?: string, page?: number, size?: number, sort?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/explorer/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (mimeType !== undefined) {
                localVarQueryParameter['mimeType'] = mimeType;
            }

            if (ownerId !== undefined) {
                localVarQueryParameter['ownerId'] = ownerId;
            }

            if (tags) {
                localVarQueryParameter['tags'] = tags.join(COLLECTION_FORMATS.csv);
            }

            if (createdFrom !== undefined) {
                localVarQueryParameter['createdFrom'] = (createdFrom as any instanceof Date) ?
                    (createdFrom as any).toISOString() :
                    createdFrom;
            }

            if (createdTo !== undefined) {
                localVarQueryParameter['createdTo'] = (createdTo as any instanceof Date) ?
                    (createdTo as any).toISOString() :
                    createdTo;
            }

            if (modifiedFrom !== undefined) {
                localVarQueryParameter['modifiedFrom'] = (modifiedFrom as any instanceof Date) ?
                    (modifiedFrom as any).toISOString() :
                    modifiedFrom;
            }

            if (modifiedTo !== undefined) {
                localVarQueryParameter['modifiedTo'] = (modifiedTo as any instanceof Date) ?
                    (modifiedTo as any).toISOString() :
                    modifiedTo;
            }

            if (folderId !== undefined) {
                localVarQueryParameter['folderId'] = folderId;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExplorerApi - functional programming interface
 */
export const ExplorerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExplorerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get breadcrumb path for a folder
         * @param {string} folderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBreadcrumb(folderId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BreadcrumbResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBreadcrumb(folderId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExplorerApi.getBreadcrumb']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List directory contents
         * @param {string} [folderId] Folder to list; omit for root
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort expression: field,asc or field,desc
         * @param {ListDirectoryTypeEnum} [type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDirectory(folderId?: string, page?: number, size?: number, sort?: string, type?: ListDirectoryTypeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DirectoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDirectory(folderId, page, size, sort, type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExplorerApi.listDirectory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search files and folders
         * @param {string} [q] Full-text search query
         * @param {SearchTypeEnum} [type] 
         * @param {string} [mimeType] 
         * @param {string} [ownerId] 
         * @param {Array<string>} [tags] 
         * @param {string} [createdFrom] 
         * @param {string} [createdTo] 
         * @param {string} [modifiedFrom] 
         * @param {string} [modifiedTo] 
         * @param {string} [folderId] Scope search to a specific folder (and descendants)
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort expression: field,asc or field,desc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async search(q?: string, type?: SearchTypeEnum, mimeType?: string, ownerId?: string, tags?: Array<string>, createdFrom?: string, createdTo?: string, modifiedFrom?: string, modifiedTo?: string, folderId?: string, page?: number, size?: number, sort?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchResultPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.search(q, type, mimeType, ownerId, tags, createdFrom, createdTo, modifiedFrom, modifiedTo, folderId, page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExplorerApi.search']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExplorerApi - factory interface
 */
export const ExplorerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExplorerApiFp(configuration)
    return {
        /**
         * 
         * @summary Get breadcrumb path for a folder
         * @param {string} folderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBreadcrumb(folderId: string, options?: RawAxiosRequestConfig): AxiosPromise<BreadcrumbResponse> {
            return localVarFp.getBreadcrumb(folderId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List directory contents
         * @param {string} [folderId] Folder to list; omit for root
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort expression: field,asc or field,desc
         * @param {ListDirectoryTypeEnum} [type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDirectory(folderId?: string, page?: number, size?: number, sort?: string, type?: ListDirectoryTypeEnum, options?: RawAxiosRequestConfig): AxiosPromise<DirectoryResponse> {
            return localVarFp.listDirectory(folderId, page, size, sort, type, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search files and folders
         * @param {string} [q] Full-text search query
         * @param {SearchTypeEnum} [type] 
         * @param {string} [mimeType] 
         * @param {string} [ownerId] 
         * @param {Array<string>} [tags] 
         * @param {string} [createdFrom] 
         * @param {string} [createdTo] 
         * @param {string} [modifiedFrom] 
         * @param {string} [modifiedTo] 
         * @param {string} [folderId] Scope search to a specific folder (and descendants)
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort expression: field,asc or field,desc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search(q?: string, type?: SearchTypeEnum, mimeType?: string, ownerId?: string, tags?: Array<string>, createdFrom?: string, createdTo?: string, modifiedFrom?: string, modifiedTo?: string, folderId?: string, page?: number, size?: number, sort?: string, options?: RawAxiosRequestConfig): AxiosPromise<SearchResultPageResponse> {
            return localVarFp.search(q, type, mimeType, ownerId, tags, createdFrom, createdTo, modifiedFrom, modifiedTo, folderId, page, size, sort, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExplorerApi - object-oriented interface
 */
export class ExplorerApi extends BaseAPI {
    /**
     * 
     * @summary Get breadcrumb path for a folder
     * @param {string} folderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getBreadcrumb(folderId: string, options?: RawAxiosRequestConfig) {
        return ExplorerApiFp(this.configuration).getBreadcrumb(folderId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List directory contents
     * @param {string} [folderId] Folder to list; omit for root
     * @param {number} [page] Zero-based page index
     * @param {number} [size] Number of items per page
     * @param {string} [sort] Sort expression: field,asc or field,desc
     * @param {ListDirectoryTypeEnum} [type] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listDirectory(folderId?: string, page?: number, size?: number, sort?: string, type?: ListDirectoryTypeEnum, options?: RawAxiosRequestConfig) {
        return ExplorerApiFp(this.configuration).listDirectory(folderId, page, size, sort, type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search files and folders
     * @param {string} [q] Full-text search query
     * @param {SearchTypeEnum} [type] 
     * @param {string} [mimeType] 
     * @param {string} [ownerId] 
     * @param {Array<string>} [tags] 
     * @param {string} [createdFrom] 
     * @param {string} [createdTo] 
     * @param {string} [modifiedFrom] 
     * @param {string} [modifiedTo] 
     * @param {string} [folderId] Scope search to a specific folder (and descendants)
     * @param {number} [page] Zero-based page index
     * @param {number} [size] Number of items per page
     * @param {string} [sort] Sort expression: field,asc or field,desc
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public search(q?: string, type?: SearchTypeEnum, mimeType?: string, ownerId?: string, tags?: Array<string>, createdFrom?: string, createdTo?: string, modifiedFrom?: string, modifiedTo?: string, folderId?: string, page?: number, size?: number, sort?: string, options?: RawAxiosRequestConfig) {
        return ExplorerApiFp(this.configuration).search(q, type, mimeType, ownerId, tags, createdFrom, createdTo, modifiedFrom, modifiedTo, folderId, page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ListDirectoryTypeEnum = {
    File: 'file',
    Folder: 'folder',
    All: 'all'
} as const;
export type ListDirectoryTypeEnum = typeof ListDirectoryTypeEnum[keyof typeof ListDirectoryTypeEnum];
export const SearchTypeEnum = {
    File: 'file',
    Folder: 'folder',
    All: 'all'
} as const;
export type SearchTypeEnum = typeof SearchTypeEnum[keyof typeof SearchTypeEnum];
