/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Document Management System API
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@dms.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BulkDownloadRequest } from '../models';
// @ts-ignore
import type { BulkUploadResponse } from '../models';
// @ts-ignore
import type { CopyRequest } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { FileResponse } from '../models';
// @ts-ignore
import type { FileVersionPageResponse } from '../models';
// @ts-ignore
import type { FileVersionResponse } from '../models';
// @ts-ignore
import type { GetFilesByFolder200Response } from '../models';
// @ts-ignore
import type { MoveRequest } from '../models';
// @ts-ignore
import type { RenameRequest } from '../models';
// @ts-ignore
import type { TagsRequest } from '../models';
/**
 * FilesApi - axios parameter creator
 */
export const FilesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Bulk download files as ZIP
         * @param {BulkDownloadRequest} bulkDownloadRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkDownload: async (bulkDownloadRequest: BulkDownloadRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkDownloadRequest' is not null or undefined
            assertParamExists('bulkDownload', 'bulkDownloadRequest', bulkDownloadRequest)
            const localVarPath = `/files/bulk-download`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/zip';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkDownloadRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Bulk upload files
         * @param {Array<File>} files Multiple file binaries
         * @param {string} [folderId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkUploadFiles: async (files: Array<File>, folderId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'files' is not null or undefined
            assertParamExists('bulkUploadFiles', 'files', files)
            const localVarPath = `/files/bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (files) {
                files.forEach((element) => {
                    localVarFormParams.append('files', element as any);
                })
            }


            if (folderId !== undefined) { 
                localVarFormParams.append('folderId', folderId as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Copy file
         * @param {string} fileId 
         * @param {CopyRequest} copyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        copyFile: async (fileId: string, copyRequest: CopyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('copyFile', 'fileId', fileId)
            // verify required parameter 'copyRequest' is not null or undefined
            assertParamExists('copyFile', 'copyRequest', copyRequest)
            const localVarPath = `/files/{fileId}/copy`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(copyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete file (moves to trash)
         * @param {string} fileId 
         * @param {boolean} [permanent] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFile: async (fileId: string, permanent?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('deleteFile', 'fileId', fileId)
            const localVarPath = `/files/{fileId}`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (permanent !== undefined) {
                localVarQueryParameter['permanent'] = permanent;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Download file
         * @param {string} fileId 
         * @param {number} [version] Specific version number; defaults to latest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadFile: async (fileId: string, version?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('downloadFile', 'fileId', fileId)
            const localVarPath = `/files/{fileId}/download`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (version !== undefined) {
                localVarQueryParameter['version'] = version;
            }

            localVarHeaderParameter['Accept'] = 'application/octet-stream,application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all files
         * @param {number} [page] Zero-indexed page number
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort criteria (e.g., createdAt,desc)
         * @param {GetAllFilesStatusEnum} [status] Filter by file status
         * @param {string} [mimeType] Filter by MIME type
         * @param {string} [search] Search in file name and tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllFiles: async (page?: number, size?: number, sort?: string, status?: GetAllFilesStatusEnum, mimeType?: string, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/files`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (mimeType !== undefined) {
                localVarQueryParameter['mimeType'] = mimeType;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get file metadata
         * @param {string} fileId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFile: async (fileId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('getFile', 'fileId', fileId)
            const localVarPath = `/files/{fileId}`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List file versions
         * @param {string} fileId 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listFileVersions: async (fileId: string, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('listFileVersions', 'fileId', fileId)
            const localVarPath = `/files/{fileId}/versions`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Move file
         * @param {string} fileId 
         * @param {MoveRequest} moveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        moveFile: async (fileId: string, moveRequest: MoveRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('moveFile', 'fileId', fileId)
            // verify required parameter 'moveRequest' is not null or undefined
            assertParamExists('moveFile', 'moveRequest', moveRequest)
            const localVarPath = `/files/{fileId}/move`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(moveRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a preview image or HTML rendition of the file.
         * @summary Get file preview
         * @param {string} fileId 
         * @param {PreviewFileFormatEnum} [format] 
         * @param {number} [page] Page number for multi-page documents
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        previewFile: async (fileId: string, format?: PreviewFileFormatEnum, page?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('previewFile', 'fileId', fileId)
            const localVarPath = `/files/{fileId}/preview`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'image/png,image/jpeg,application/pdf,text/html';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Rename file
         * @param {string} fileId 
         * @param {RenameRequest} renameRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renameFile: async (fileId: string, renameRequest: RenameRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('renameFile', 'fileId', fileId)
            // verify required parameter 'renameRequest' is not null or undefined
            assertParamExists('renameFile', 'renameRequest', renameRequest)
            const localVarPath = `/files/{fileId}`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(renameRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Restore file from trash
         * @param {string} fileId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restoreFile: async (fileId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('restoreFile', 'fileId', fileId)
            const localVarPath = `/files/{fileId}/restore`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Restore a specific file version
         * @param {string} fileId 
         * @param {string} versionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restoreFileVersion: async (fileId: string, versionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('restoreFileVersion', 'fileId', fileId)
            // verify required parameter 'versionId' is not null or undefined
            assertParamExists('restoreFileVersion', 'versionId', versionId)
            const localVarPath = `/files/{fileId}/versions/{versionId}/restore`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)))
                .replace(`{${"versionId"}}`, encodeURIComponent(String(versionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Set tags on file
         * @param {string} fileId 
         * @param {TagsRequest} tagsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setFileTags: async (fileId: string, tagsRequest: TagsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('setFileTags', 'fileId', fileId)
            // verify required parameter 'tagsRequest' is not null or undefined
            assertParamExists('setFileTags', 'tagsRequest', tagsRequest)
            const localVarPath = `/files/{fileId}/tags`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(tagsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload single file
         * @param {File} file File content
         * @param {string} [folderId] Target folder; root if omitted
         * @param {string} [tags] Comma-separated tags
         * @param {string} [description] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFile: async (file: File, folderId?: string, tags?: string, description?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadFile', 'file', file)
            const localVarPath = `/files`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }

            if (folderId !== undefined) { 
                localVarFormParams.append('folderId', folderId as any);
            }

            if (tags !== undefined) { 
                localVarFormParams.append('tags', tags as any);
            }

            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload new file version
         * @param {string} fileId 
         * @param {File} file 
         * @param {string} [comment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFileVersion: async (fileId: string, file: File, comment?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fileId' is not null or undefined
            assertParamExists('uploadFileVersion', 'fileId', fileId)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadFileVersion', 'file', file)
            const localVarPath = `/files/{fileId}/versions`
                .replace(`{${"fileId"}}`, encodeURIComponent(String(fileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }

            if (comment !== undefined) { 
                localVarFormParams.append('comment', comment as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FilesApi - functional programming interface
 */
export const FilesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FilesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Bulk download files as ZIP
         * @param {BulkDownloadRequest} bulkDownloadRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkDownload(bulkDownloadRequest: BulkDownloadRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkDownload(bulkDownloadRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.bulkDownload']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Bulk upload files
         * @param {Array<File>} files Multiple file binaries
         * @param {string} [folderId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkUploadFiles(files: Array<File>, folderId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkUploadResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkUploadFiles(files, folderId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.bulkUploadFiles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Copy file
         * @param {string} fileId 
         * @param {CopyRequest} copyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async copyFile(fileId: string, copyRequest: CopyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.copyFile(fileId, copyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.copyFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete file (moves to trash)
         * @param {string} fileId 
         * @param {boolean} [permanent] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteFile(fileId: string, permanent?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteFile(fileId, permanent, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.deleteFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Download file
         * @param {string} fileId 
         * @param {number} [version] Specific version number; defaults to latest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadFile(fileId: string, version?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadFile(fileId, version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.downloadFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all files
         * @param {number} [page] Zero-indexed page number
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort criteria (e.g., createdAt,desc)
         * @param {GetAllFilesStatusEnum} [status] Filter by file status
         * @param {string} [mimeType] Filter by MIME type
         * @param {string} [search] Search in file name and tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllFiles(page?: number, size?: number, sort?: string, status?: GetAllFilesStatusEnum, mimeType?: string, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFilesByFolder200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllFiles(page, size, sort, status, mimeType, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.getAllFiles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get file metadata
         * @param {string} fileId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFile(fileId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFile(fileId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.getFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List file versions
         * @param {string} fileId 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listFileVersions(fileId: string, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileVersionPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listFileVersions(fileId, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.listFileVersions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Move file
         * @param {string} fileId 
         * @param {MoveRequest} moveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async moveFile(fileId: string, moveRequest: MoveRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.moveFile(fileId, moveRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.moveFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a preview image or HTML rendition of the file.
         * @summary Get file preview
         * @param {string} fileId 
         * @param {PreviewFileFormatEnum} [format] 
         * @param {number} [page] Page number for multi-page documents
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async previewFile(fileId: string, format?: PreviewFileFormatEnum, page?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.previewFile(fileId, format, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.previewFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Rename file
         * @param {string} fileId 
         * @param {RenameRequest} renameRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async renameFile(fileId: string, renameRequest: RenameRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.renameFile(fileId, renameRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.renameFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Restore file from trash
         * @param {string} fileId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async restoreFile(fileId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.restoreFile(fileId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.restoreFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Restore a specific file version
         * @param {string} fileId 
         * @param {string} versionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async restoreFileVersion(fileId: string, versionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.restoreFileVersion(fileId, versionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.restoreFileVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Set tags on file
         * @param {string} fileId 
         * @param {TagsRequest} tagsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setFileTags(fileId: string, tagsRequest: TagsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setFileTags(fileId, tagsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.setFileTags']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Upload single file
         * @param {File} file File content
         * @param {string} [folderId] Target folder; root if omitted
         * @param {string} [tags] Comma-separated tags
         * @param {string} [description] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFile(file: File, folderId?: string, tags?: string, description?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadFile(file, folderId, tags, description, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.uploadFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Upload new file version
         * @param {string} fileId 
         * @param {File} file 
         * @param {string} [comment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFileVersion(fileId: string, file: File, comment?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FileVersionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadFileVersion(fileId, file, comment, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FilesApi.uploadFileVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FilesApi - factory interface
 */
export const FilesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FilesApiFp(configuration)
    return {
        /**
         * 
         * @summary Bulk download files as ZIP
         * @param {BulkDownloadRequest} bulkDownloadRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkDownload(bulkDownloadRequest: BulkDownloadRequest, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.bulkDownload(bulkDownloadRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Bulk upload files
         * @param {Array<File>} files Multiple file binaries
         * @param {string} [folderId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkUploadFiles(files: Array<File>, folderId?: string, options?: RawAxiosRequestConfig): AxiosPromise<BulkUploadResponse> {
            return localVarFp.bulkUploadFiles(files, folderId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Copy file
         * @param {string} fileId 
         * @param {CopyRequest} copyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        copyFile(fileId: string, copyRequest: CopyRequest, options?: RawAxiosRequestConfig): AxiosPromise<FileResponse> {
            return localVarFp.copyFile(fileId, copyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete file (moves to trash)
         * @param {string} fileId 
         * @param {boolean} [permanent] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFile(fileId: string, permanent?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteFile(fileId, permanent, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Download file
         * @param {string} fileId 
         * @param {number} [version] Specific version number; defaults to latest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadFile(fileId: string, version?: number, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.downloadFile(fileId, version, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all files
         * @param {number} [page] Zero-indexed page number
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort criteria (e.g., createdAt,desc)
         * @param {GetAllFilesStatusEnum} [status] Filter by file status
         * @param {string} [mimeType] Filter by MIME type
         * @param {string} [search] Search in file name and tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllFiles(page?: number, size?: number, sort?: string, status?: GetAllFilesStatusEnum, mimeType?: string, search?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetFilesByFolder200Response> {
            return localVarFp.getAllFiles(page, size, sort, status, mimeType, search, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get file metadata
         * @param {string} fileId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFile(fileId: string, options?: RawAxiosRequestConfig): AxiosPromise<FileResponse> {
            return localVarFp.getFile(fileId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List file versions
         * @param {string} fileId 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listFileVersions(fileId: string, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<FileVersionPageResponse> {
            return localVarFp.listFileVersions(fileId, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Move file
         * @param {string} fileId 
         * @param {MoveRequest} moveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        moveFile(fileId: string, moveRequest: MoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<FileResponse> {
            return localVarFp.moveFile(fileId, moveRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a preview image or HTML rendition of the file.
         * @summary Get file preview
         * @param {string} fileId 
         * @param {PreviewFileFormatEnum} [format] 
         * @param {number} [page] Page number for multi-page documents
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        previewFile(fileId: string, format?: PreviewFileFormatEnum, page?: number, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.previewFile(fileId, format, page, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Rename file
         * @param {string} fileId 
         * @param {RenameRequest} renameRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renameFile(fileId: string, renameRequest: RenameRequest, options?: RawAxiosRequestConfig): AxiosPromise<FileResponse> {
            return localVarFp.renameFile(fileId, renameRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Restore file from trash
         * @param {string} fileId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restoreFile(fileId: string, options?: RawAxiosRequestConfig): AxiosPromise<FileResponse> {
            return localVarFp.restoreFile(fileId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Restore a specific file version
         * @param {string} fileId 
         * @param {string} versionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restoreFileVersion(fileId: string, versionId: string, options?: RawAxiosRequestConfig): AxiosPromise<FileResponse> {
            return localVarFp.restoreFileVersion(fileId, versionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Set tags on file
         * @param {string} fileId 
         * @param {TagsRequest} tagsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setFileTags(fileId: string, tagsRequest: TagsRequest, options?: RawAxiosRequestConfig): AxiosPromise<FileResponse> {
            return localVarFp.setFileTags(fileId, tagsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload single file
         * @param {File} file File content
         * @param {string} [folderId] Target folder; root if omitted
         * @param {string} [tags] Comma-separated tags
         * @param {string} [description] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFile(file: File, folderId?: string, tags?: string, description?: string, options?: RawAxiosRequestConfig): AxiosPromise<FileResponse> {
            return localVarFp.uploadFile(file, folderId, tags, description, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload new file version
         * @param {string} fileId 
         * @param {File} file 
         * @param {string} [comment] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFileVersion(fileId: string, file: File, comment?: string, options?: RawAxiosRequestConfig): AxiosPromise<FileVersionResponse> {
            return localVarFp.uploadFileVersion(fileId, file, comment, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FilesApi - object-oriented interface
 */
export class FilesApi extends BaseAPI {
    /**
     * 
     * @summary Bulk download files as ZIP
     * @param {BulkDownloadRequest} bulkDownloadRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public bulkDownload(bulkDownloadRequest: BulkDownloadRequest, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).bulkDownload(bulkDownloadRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Bulk upload files
     * @param {Array<File>} files Multiple file binaries
     * @param {string} [folderId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public bulkUploadFiles(files: Array<File>, folderId?: string, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).bulkUploadFiles(files, folderId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Copy file
     * @param {string} fileId 
     * @param {CopyRequest} copyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public copyFile(fileId: string, copyRequest: CopyRequest, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).copyFile(fileId, copyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete file (moves to trash)
     * @param {string} fileId 
     * @param {boolean} [permanent] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteFile(fileId: string, permanent?: boolean, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).deleteFile(fileId, permanent, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Download file
     * @param {string} fileId 
     * @param {number} [version] Specific version number; defaults to latest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public downloadFile(fileId: string, version?: number, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).downloadFile(fileId, version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all files
     * @param {number} [page] Zero-indexed page number
     * @param {number} [size] Number of items per page
     * @param {string} [sort] Sort criteria (e.g., createdAt,desc)
     * @param {GetAllFilesStatusEnum} [status] Filter by file status
     * @param {string} [mimeType] Filter by MIME type
     * @param {string} [search] Search in file name and tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllFiles(page?: number, size?: number, sort?: string, status?: GetAllFilesStatusEnum, mimeType?: string, search?: string, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).getAllFiles(page, size, sort, status, mimeType, search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get file metadata
     * @param {string} fileId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getFile(fileId: string, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).getFile(fileId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List file versions
     * @param {string} fileId 
     * @param {number} [page] Zero-based page index
     * @param {number} [size] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listFileVersions(fileId: string, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).listFileVersions(fileId, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Move file
     * @param {string} fileId 
     * @param {MoveRequest} moveRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public moveFile(fileId: string, moveRequest: MoveRequest, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).moveFile(fileId, moveRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a preview image or HTML rendition of the file.
     * @summary Get file preview
     * @param {string} fileId 
     * @param {PreviewFileFormatEnum} [format] 
     * @param {number} [page] Page number for multi-page documents
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public previewFile(fileId: string, format?: PreviewFileFormatEnum, page?: number, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).previewFile(fileId, format, page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Rename file
     * @param {string} fileId 
     * @param {RenameRequest} renameRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public renameFile(fileId: string, renameRequest: RenameRequest, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).renameFile(fileId, renameRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Restore file from trash
     * @param {string} fileId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public restoreFile(fileId: string, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).restoreFile(fileId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Restore a specific file version
     * @param {string} fileId 
     * @param {string} versionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public restoreFileVersion(fileId: string, versionId: string, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).restoreFileVersion(fileId, versionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Set tags on file
     * @param {string} fileId 
     * @param {TagsRequest} tagsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public setFileTags(fileId: string, tagsRequest: TagsRequest, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).setFileTags(fileId, tagsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload single file
     * @param {File} file File content
     * @param {string} [folderId] Target folder; root if omitted
     * @param {string} [tags] Comma-separated tags
     * @param {string} [description] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public uploadFile(file: File, folderId?: string, tags?: string, description?: string, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).uploadFile(file, folderId, tags, description, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload new file version
     * @param {string} fileId 
     * @param {File} file 
     * @param {string} [comment] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public uploadFileVersion(fileId: string, file: File, comment?: string, options?: RawAxiosRequestConfig) {
        return FilesApiFp(this.configuration).uploadFileVersion(fileId, file, comment, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetAllFilesStatusEnum = {
    Active: 'active',
    Trashed: 'trashed',
    Archived: 'archived'
} as const;
export type GetAllFilesStatusEnum = typeof GetAllFilesStatusEnum[keyof typeof GetAllFilesStatusEnum];
export const PreviewFileFormatEnum = {
    Png: 'png',
    Jpg: 'jpg',
    Pdf: 'pdf',
    Html: 'html'
} as const;
export type PreviewFileFormatEnum = typeof PreviewFileFormatEnum[keyof typeof PreviewFileFormatEnum];
