/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Document Management System API
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@dms.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CopyRequest } from '../models';
// @ts-ignore
import type { CreateFolderRequest } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { FolderResponse } from '../models';
// @ts-ignore
import type { GetFilesByFolder200Response } from '../models';
// @ts-ignore
import type { MoveRequest } from '../models';
// @ts-ignore
import type { RenameRequest } from '../models';
/**
 * FoldersApi - axios parameter creator
 */
export const FoldersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Copy folder
         * @param {string} folderId 
         * @param {CopyRequest} copyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        copyFolder: async (folderId: string, copyRequest: CopyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'folderId' is not null or undefined
            assertParamExists('copyFolder', 'folderId', folderId)
            // verify required parameter 'copyRequest' is not null or undefined
            assertParamExists('copyFolder', 'copyRequest', copyRequest)
            const localVarPath = `/folders/{folderId}/copy`
                .replace(`{${"folderId"}}`, encodeURIComponent(String(folderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(copyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create folder
         * @param {CreateFolderRequest} createFolderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createFolder: async (createFolderRequest: CreateFolderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createFolderRequest' is not null or undefined
            assertParamExists('createFolder', 'createFolderRequest', createFolderRequest)
            const localVarPath = `/folders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createFolderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete folder (moves to trash)
         * @param {string} folderId 
         * @param {boolean} [permanent] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFolder: async (folderId: string, permanent?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'folderId' is not null or undefined
            assertParamExists('deleteFolder', 'folderId', folderId)
            const localVarPath = `/folders/{folderId}`
                .replace(`{${"folderId"}}`, encodeURIComponent(String(folderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (permanent !== undefined) {
                localVarQueryParameter['permanent'] = permanent;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all files in folder
         * @param {string} folderId 
         * @param {number} [page] Zero-indexed page number
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort criteria (e.g., createdAt,desc)
         * @param {GetFilesByFolderStatusEnum} [status] Filter by file status
         * @param {string} [mimeType] Filter by MIME type
         * @param {string} [search] Search in file name and tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFilesByFolder: async (folderId: string, page?: number, size?: number, sort?: string, status?: GetFilesByFolderStatusEnum, mimeType?: string, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'folderId' is not null or undefined
            assertParamExists('getFilesByFolder', 'folderId', folderId)
            const localVarPath = `/folders/{folderId}/files`
                .replace(`{${"folderId"}}`, encodeURIComponent(String(folderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (mimeType !== undefined) {
                localVarQueryParameter['mimeType'] = mimeType;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get folder metadata
         * @param {string} folderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFolder: async (folderId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'folderId' is not null or undefined
            assertParamExists('getFolder', 'folderId', folderId)
            const localVarPath = `/folders/{folderId}`
                .replace(`{${"folderId"}}`, encodeURIComponent(String(folderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Move folder
         * @param {string} folderId 
         * @param {MoveRequest} moveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        moveFolder: async (folderId: string, moveRequest: MoveRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'folderId' is not null or undefined
            assertParamExists('moveFolder', 'folderId', folderId)
            // verify required parameter 'moveRequest' is not null or undefined
            assertParamExists('moveFolder', 'moveRequest', moveRequest)
            const localVarPath = `/folders/{folderId}/move`
                .replace(`{${"folderId"}}`, encodeURIComponent(String(folderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(moveRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Rename folder
         * @param {string} folderId 
         * @param {RenameRequest} renameRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renameFolder: async (folderId: string, renameRequest: RenameRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'folderId' is not null or undefined
            assertParamExists('renameFolder', 'folderId', folderId)
            // verify required parameter 'renameRequest' is not null or undefined
            assertParamExists('renameFolder', 'renameRequest', renameRequest)
            const localVarPath = `/folders/{folderId}`
                .replace(`{${"folderId"}}`, encodeURIComponent(String(folderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(renameRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Restore folder from trash
         * @param {string} folderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restoreFolder: async (folderId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'folderId' is not null or undefined
            assertParamExists('restoreFolder', 'folderId', folderId)
            const localVarPath = `/folders/{folderId}/restore`
                .replace(`{${"folderId"}}`, encodeURIComponent(String(folderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FoldersApi - functional programming interface
 */
export const FoldersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FoldersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Copy folder
         * @param {string} folderId 
         * @param {CopyRequest} copyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async copyFolder(folderId: string, copyRequest: CopyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FolderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.copyFolder(folderId, copyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FoldersApi.copyFolder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create folder
         * @param {CreateFolderRequest} createFolderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createFolder(createFolderRequest: CreateFolderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FolderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createFolder(createFolderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FoldersApi.createFolder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete folder (moves to trash)
         * @param {string} folderId 
         * @param {boolean} [permanent] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteFolder(folderId: string, permanent?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteFolder(folderId, permanent, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FoldersApi.deleteFolder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all files in folder
         * @param {string} folderId 
         * @param {number} [page] Zero-indexed page number
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort criteria (e.g., createdAt,desc)
         * @param {GetFilesByFolderStatusEnum} [status] Filter by file status
         * @param {string} [mimeType] Filter by MIME type
         * @param {string} [search] Search in file name and tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFilesByFolder(folderId: string, page?: number, size?: number, sort?: string, status?: GetFilesByFolderStatusEnum, mimeType?: string, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFilesByFolder200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFilesByFolder(folderId, page, size, sort, status, mimeType, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FoldersApi.getFilesByFolder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get folder metadata
         * @param {string} folderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFolder(folderId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FolderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFolder(folderId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FoldersApi.getFolder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Move folder
         * @param {string} folderId 
         * @param {MoveRequest} moveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async moveFolder(folderId: string, moveRequest: MoveRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FolderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.moveFolder(folderId, moveRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FoldersApi.moveFolder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Rename folder
         * @param {string} folderId 
         * @param {RenameRequest} renameRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async renameFolder(folderId: string, renameRequest: RenameRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FolderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.renameFolder(folderId, renameRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FoldersApi.renameFolder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Restore folder from trash
         * @param {string} folderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async restoreFolder(folderId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FolderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.restoreFolder(folderId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FoldersApi.restoreFolder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FoldersApi - factory interface
 */
export const FoldersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FoldersApiFp(configuration)
    return {
        /**
         * 
         * @summary Copy folder
         * @param {string} folderId 
         * @param {CopyRequest} copyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        copyFolder(folderId: string, copyRequest: CopyRequest, options?: RawAxiosRequestConfig): AxiosPromise<FolderResponse> {
            return localVarFp.copyFolder(folderId, copyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create folder
         * @param {CreateFolderRequest} createFolderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createFolder(createFolderRequest: CreateFolderRequest, options?: RawAxiosRequestConfig): AxiosPromise<FolderResponse> {
            return localVarFp.createFolder(createFolderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete folder (moves to trash)
         * @param {string} folderId 
         * @param {boolean} [permanent] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFolder(folderId: string, permanent?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteFolder(folderId, permanent, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all files in folder
         * @param {string} folderId 
         * @param {number} [page] Zero-indexed page number
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort criteria (e.g., createdAt,desc)
         * @param {GetFilesByFolderStatusEnum} [status] Filter by file status
         * @param {string} [mimeType] Filter by MIME type
         * @param {string} [search] Search in file name and tags
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFilesByFolder(folderId: string, page?: number, size?: number, sort?: string, status?: GetFilesByFolderStatusEnum, mimeType?: string, search?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetFilesByFolder200Response> {
            return localVarFp.getFilesByFolder(folderId, page, size, sort, status, mimeType, search, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get folder metadata
         * @param {string} folderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFolder(folderId: string, options?: RawAxiosRequestConfig): AxiosPromise<FolderResponse> {
            return localVarFp.getFolder(folderId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Move folder
         * @param {string} folderId 
         * @param {MoveRequest} moveRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        moveFolder(folderId: string, moveRequest: MoveRequest, options?: RawAxiosRequestConfig): AxiosPromise<FolderResponse> {
            return localVarFp.moveFolder(folderId, moveRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Rename folder
         * @param {string} folderId 
         * @param {RenameRequest} renameRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renameFolder(folderId: string, renameRequest: RenameRequest, options?: RawAxiosRequestConfig): AxiosPromise<FolderResponse> {
            return localVarFp.renameFolder(folderId, renameRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Restore folder from trash
         * @param {string} folderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restoreFolder(folderId: string, options?: RawAxiosRequestConfig): AxiosPromise<FolderResponse> {
            return localVarFp.restoreFolder(folderId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FoldersApi - object-oriented interface
 */
export class FoldersApi extends BaseAPI {
    /**
     * 
     * @summary Copy folder
     * @param {string} folderId 
     * @param {CopyRequest} copyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public copyFolder(folderId: string, copyRequest: CopyRequest, options?: RawAxiosRequestConfig) {
        return FoldersApiFp(this.configuration).copyFolder(folderId, copyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create folder
     * @param {CreateFolderRequest} createFolderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createFolder(createFolderRequest: CreateFolderRequest, options?: RawAxiosRequestConfig) {
        return FoldersApiFp(this.configuration).createFolder(createFolderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete folder (moves to trash)
     * @param {string} folderId 
     * @param {boolean} [permanent] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteFolder(folderId: string, permanent?: boolean, options?: RawAxiosRequestConfig) {
        return FoldersApiFp(this.configuration).deleteFolder(folderId, permanent, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all files in folder
     * @param {string} folderId 
     * @param {number} [page] Zero-indexed page number
     * @param {number} [size] Number of items per page
     * @param {string} [sort] Sort criteria (e.g., createdAt,desc)
     * @param {GetFilesByFolderStatusEnum} [status] Filter by file status
     * @param {string} [mimeType] Filter by MIME type
     * @param {string} [search] Search in file name and tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getFilesByFolder(folderId: string, page?: number, size?: number, sort?: string, status?: GetFilesByFolderStatusEnum, mimeType?: string, search?: string, options?: RawAxiosRequestConfig) {
        return FoldersApiFp(this.configuration).getFilesByFolder(folderId, page, size, sort, status, mimeType, search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get folder metadata
     * @param {string} folderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getFolder(folderId: string, options?: RawAxiosRequestConfig) {
        return FoldersApiFp(this.configuration).getFolder(folderId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Move folder
     * @param {string} folderId 
     * @param {MoveRequest} moveRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public moveFolder(folderId: string, moveRequest: MoveRequest, options?: RawAxiosRequestConfig) {
        return FoldersApiFp(this.configuration).moveFolder(folderId, moveRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Rename folder
     * @param {string} folderId 
     * @param {RenameRequest} renameRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public renameFolder(folderId: string, renameRequest: RenameRequest, options?: RawAxiosRequestConfig) {
        return FoldersApiFp(this.configuration).renameFolder(folderId, renameRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Restore folder from trash
     * @param {string} folderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public restoreFolder(folderId: string, options?: RawAxiosRequestConfig) {
        return FoldersApiFp(this.configuration).restoreFolder(folderId, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetFilesByFolderStatusEnum = {
    Active: 'active',
    Trashed: 'trashed',
    Archived: 'archived'
} as const;
export type GetFilesByFolderStatusEnum = typeof GetFilesByFolderStatusEnum[keyof typeof GetFilesByFolderStatusEnum];
