/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Document Management System API
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@dms.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AclEntryResponse } from '../models';
// @ts-ignore
import type { AclResponse } from '../models';
// @ts-ignore
import type { CreateShareRequest } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { PublicLinkRequest } from '../models';
// @ts-ignore
import type { PublicLinkResponse } from '../models';
// @ts-ignore
import type { ShareResponse } from '../models';
// @ts-ignore
import type { UpdatePermissionRequest } from '../models';
/**
 * SharingApi - axios parameter creator
 */
export const SharingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Share file or folder with users/teams
         * @param {CreateShareRequest} createShareRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createShare: async (createShareRequest: CreateShareRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createShareRequest' is not null or undefined
            assertParamExists('createShare', 'createShareRequest', createShareRequest)
            const localVarPath = `/shares`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createShareRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Generate public share link
         * @param {PublicLinkRequest} publicLinkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generatePublicLink: async (publicLinkRequest: PublicLinkRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'publicLinkRequest' is not null or undefined
            assertParamExists('generatePublicLink', 'publicLinkRequest', publicLinkRequest)
            const localVarPath = `/shares/public-links`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(publicLinkRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get ACL for a resource
         * @param {GetAclResourceTypeEnum} resourceType 
         * @param {string} resourceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAcl: async (resourceType: GetAclResourceTypeEnum, resourceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resourceType' is not null or undefined
            assertParamExists('getAcl', 'resourceType', resourceType)
            // verify required parameter 'resourceId' is not null or undefined
            assertParamExists('getAcl', 'resourceId', resourceId)
            const localVarPath = `/shares/{resourceType}/{resourceId}`
                .replace(`{${"resourceType"}}`, encodeURIComponent(String(resourceType)))
                .replace(`{${"resourceId"}}`, encodeURIComponent(String(resourceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Revoke access for a principal
         * @param {RevokeAccessResourceTypeEnum} resourceType 
         * @param {string} resourceId 
         * @param {string} principalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeAccess: async (resourceType: RevokeAccessResourceTypeEnum, resourceId: string, principalId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resourceType' is not null or undefined
            assertParamExists('revokeAccess', 'resourceType', resourceType)
            // verify required parameter 'resourceId' is not null or undefined
            assertParamExists('revokeAccess', 'resourceId', resourceId)
            // verify required parameter 'principalId' is not null or undefined
            assertParamExists('revokeAccess', 'principalId', principalId)
            const localVarPath = `/shares/{resourceType}/{resourceId}/entries/{principalId}`
                .replace(`{${"resourceType"}}`, encodeURIComponent(String(resourceType)))
                .replace(`{${"resourceId"}}`, encodeURIComponent(String(resourceId)))
                .replace(`{${"principalId"}}`, encodeURIComponent(String(principalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Revoke all sharing for a resource
         * @param {RevokeAllSharesResourceTypeEnum} resourceType 
         * @param {string} resourceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeAllShares: async (resourceType: RevokeAllSharesResourceTypeEnum, resourceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resourceType' is not null or undefined
            assertParamExists('revokeAllShares', 'resourceType', resourceType)
            // verify required parameter 'resourceId' is not null or undefined
            assertParamExists('revokeAllShares', 'resourceId', resourceId)
            const localVarPath = `/shares/{resourceType}/{resourceId}`
                .replace(`{${"resourceType"}}`, encodeURIComponent(String(resourceType)))
                .replace(`{${"resourceId"}}`, encodeURIComponent(String(resourceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Revoke public link
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokePublicLink: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('revokePublicLink', 'token', token)
            const localVarPath = `/shares/public-links/{token}`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update permission for a principal
         * @param {UpdatePermissionResourceTypeEnum} resourceType 
         * @param {string} resourceId 
         * @param {string} principalId 
         * @param {UpdatePermissionRequest} updatePermissionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePermission: async (resourceType: UpdatePermissionResourceTypeEnum, resourceId: string, principalId: string, updatePermissionRequest: UpdatePermissionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'resourceType' is not null or undefined
            assertParamExists('updatePermission', 'resourceType', resourceType)
            // verify required parameter 'resourceId' is not null or undefined
            assertParamExists('updatePermission', 'resourceId', resourceId)
            // verify required parameter 'principalId' is not null or undefined
            assertParamExists('updatePermission', 'principalId', principalId)
            // verify required parameter 'updatePermissionRequest' is not null or undefined
            assertParamExists('updatePermission', 'updatePermissionRequest', updatePermissionRequest)
            const localVarPath = `/shares/{resourceType}/{resourceId}/entries/{principalId}`
                .replace(`{${"resourceType"}}`, encodeURIComponent(String(resourceType)))
                .replace(`{${"resourceId"}}`, encodeURIComponent(String(resourceId)))
                .replace(`{${"principalId"}}`, encodeURIComponent(String(principalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePermissionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SharingApi - functional programming interface
 */
export const SharingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SharingApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Share file or folder with users/teams
         * @param {CreateShareRequest} createShareRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createShare(createShareRequest: CreateShareRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ShareResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createShare(createShareRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SharingApi.createShare']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Generate public share link
         * @param {PublicLinkRequest} publicLinkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generatePublicLink(publicLinkRequest: PublicLinkRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PublicLinkResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generatePublicLink(publicLinkRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SharingApi.generatePublicLink']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get ACL for a resource
         * @param {GetAclResourceTypeEnum} resourceType 
         * @param {string} resourceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAcl(resourceType: GetAclResourceTypeEnum, resourceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AclResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAcl(resourceType, resourceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SharingApi.getAcl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Revoke access for a principal
         * @param {RevokeAccessResourceTypeEnum} resourceType 
         * @param {string} resourceId 
         * @param {string} principalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeAccess(resourceType: RevokeAccessResourceTypeEnum, resourceId: string, principalId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.revokeAccess(resourceType, resourceId, principalId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SharingApi.revokeAccess']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Revoke all sharing for a resource
         * @param {RevokeAllSharesResourceTypeEnum} resourceType 
         * @param {string} resourceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeAllShares(resourceType: RevokeAllSharesResourceTypeEnum, resourceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.revokeAllShares(resourceType, resourceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SharingApi.revokeAllShares']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Revoke public link
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokePublicLink(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.revokePublicLink(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SharingApi.revokePublicLink']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update permission for a principal
         * @param {UpdatePermissionResourceTypeEnum} resourceType 
         * @param {string} resourceId 
         * @param {string} principalId 
         * @param {UpdatePermissionRequest} updatePermissionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePermission(resourceType: UpdatePermissionResourceTypeEnum, resourceId: string, principalId: string, updatePermissionRequest: UpdatePermissionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AclEntryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePermission(resourceType, resourceId, principalId, updatePermissionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SharingApi.updatePermission']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SharingApi - factory interface
 */
export const SharingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SharingApiFp(configuration)
    return {
        /**
         * 
         * @summary Share file or folder with users/teams
         * @param {CreateShareRequest} createShareRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createShare(createShareRequest: CreateShareRequest, options?: RawAxiosRequestConfig): AxiosPromise<ShareResponse> {
            return localVarFp.createShare(createShareRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Generate public share link
         * @param {PublicLinkRequest} publicLinkRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generatePublicLink(publicLinkRequest: PublicLinkRequest, options?: RawAxiosRequestConfig): AxiosPromise<PublicLinkResponse> {
            return localVarFp.generatePublicLink(publicLinkRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get ACL for a resource
         * @param {GetAclResourceTypeEnum} resourceType 
         * @param {string} resourceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAcl(resourceType: GetAclResourceTypeEnum, resourceId: string, options?: RawAxiosRequestConfig): AxiosPromise<AclResponse> {
            return localVarFp.getAcl(resourceType, resourceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Revoke access for a principal
         * @param {RevokeAccessResourceTypeEnum} resourceType 
         * @param {string} resourceId 
         * @param {string} principalId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeAccess(resourceType: RevokeAccessResourceTypeEnum, resourceId: string, principalId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.revokeAccess(resourceType, resourceId, principalId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Revoke all sharing for a resource
         * @param {RevokeAllSharesResourceTypeEnum} resourceType 
         * @param {string} resourceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeAllShares(resourceType: RevokeAllSharesResourceTypeEnum, resourceId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.revokeAllShares(resourceType, resourceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Revoke public link
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokePublicLink(token: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.revokePublicLink(token, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update permission for a principal
         * @param {UpdatePermissionResourceTypeEnum} resourceType 
         * @param {string} resourceId 
         * @param {string} principalId 
         * @param {UpdatePermissionRequest} updatePermissionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePermission(resourceType: UpdatePermissionResourceTypeEnum, resourceId: string, principalId: string, updatePermissionRequest: UpdatePermissionRequest, options?: RawAxiosRequestConfig): AxiosPromise<AclEntryResponse> {
            return localVarFp.updatePermission(resourceType, resourceId, principalId, updatePermissionRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SharingApi - object-oriented interface
 */
export class SharingApi extends BaseAPI {
    /**
     * 
     * @summary Share file or folder with users/teams
     * @param {CreateShareRequest} createShareRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createShare(createShareRequest: CreateShareRequest, options?: RawAxiosRequestConfig) {
        return SharingApiFp(this.configuration).createShare(createShareRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Generate public share link
     * @param {PublicLinkRequest} publicLinkRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public generatePublicLink(publicLinkRequest: PublicLinkRequest, options?: RawAxiosRequestConfig) {
        return SharingApiFp(this.configuration).generatePublicLink(publicLinkRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get ACL for a resource
     * @param {GetAclResourceTypeEnum} resourceType 
     * @param {string} resourceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAcl(resourceType: GetAclResourceTypeEnum, resourceId: string, options?: RawAxiosRequestConfig) {
        return SharingApiFp(this.configuration).getAcl(resourceType, resourceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Revoke access for a principal
     * @param {RevokeAccessResourceTypeEnum} resourceType 
     * @param {string} resourceId 
     * @param {string} principalId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public revokeAccess(resourceType: RevokeAccessResourceTypeEnum, resourceId: string, principalId: string, options?: RawAxiosRequestConfig) {
        return SharingApiFp(this.configuration).revokeAccess(resourceType, resourceId, principalId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Revoke all sharing for a resource
     * @param {RevokeAllSharesResourceTypeEnum} resourceType 
     * @param {string} resourceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public revokeAllShares(resourceType: RevokeAllSharesResourceTypeEnum, resourceId: string, options?: RawAxiosRequestConfig) {
        return SharingApiFp(this.configuration).revokeAllShares(resourceType, resourceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Revoke public link
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public revokePublicLink(token: string, options?: RawAxiosRequestConfig) {
        return SharingApiFp(this.configuration).revokePublicLink(token, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update permission for a principal
     * @param {UpdatePermissionResourceTypeEnum} resourceType 
     * @param {string} resourceId 
     * @param {string} principalId 
     * @param {UpdatePermissionRequest} updatePermissionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updatePermission(resourceType: UpdatePermissionResourceTypeEnum, resourceId: string, principalId: string, updatePermissionRequest: UpdatePermissionRequest, options?: RawAxiosRequestConfig) {
        return SharingApiFp(this.configuration).updatePermission(resourceType, resourceId, principalId, updatePermissionRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetAclResourceTypeEnum = {
    File: 'file',
    Folder: 'folder'
} as const;
export type GetAclResourceTypeEnum = typeof GetAclResourceTypeEnum[keyof typeof GetAclResourceTypeEnum];
export const RevokeAccessResourceTypeEnum = {
    File: 'file',
    Folder: 'folder'
} as const;
export type RevokeAccessResourceTypeEnum = typeof RevokeAccessResourceTypeEnum[keyof typeof RevokeAccessResourceTypeEnum];
export const RevokeAllSharesResourceTypeEnum = {
    File: 'file',
    Folder: 'folder'
} as const;
export type RevokeAllSharesResourceTypeEnum = typeof RevokeAllSharesResourceTypeEnum[keyof typeof RevokeAllSharesResourceTypeEnum];
export const UpdatePermissionResourceTypeEnum = {
    File: 'file',
    Folder: 'folder'
} as const;
export type UpdatePermissionResourceTypeEnum = typeof UpdatePermissionResourceTypeEnum[keyof typeof UpdatePermissionResourceTypeEnum];
