/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Document Management System API
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@dms.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateWorkflowRequest } from '../models';
// @ts-ignore
import type { CreateWorkflowTemplateRequest } from '../models';
// @ts-ignore
import type { WorkflowDecisionRequest } from '../models';
// @ts-ignore
import type { WorkflowHistoryPageResponse } from '../models';
// @ts-ignore
import type { WorkflowInstancePageResponse } from '../models';
// @ts-ignore
import type { WorkflowInstanceResponse } from '../models';
// @ts-ignore
import type { WorkflowSubmitRequest } from '../models';
// @ts-ignore
import type { WorkflowTemplatePageResponse } from '../models';
// @ts-ignore
import type { WorkflowTemplateResponse } from '../models';
/**
 * WorkflowsApi - axios parameter creator
 */
export const WorkflowsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Approve workflow step
         * @param {string} workflowId 
         * @param {string} stepId 
         * @param {WorkflowDecisionRequest} [workflowDecisionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveStep: async (workflowId: string, stepId: string, workflowDecisionRequest?: WorkflowDecisionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workflowId' is not null or undefined
            assertParamExists('approveStep', 'workflowId', workflowId)
            // verify required parameter 'stepId' is not null or undefined
            assertParamExists('approveStep', 'stepId', stepId)
            const localVarPath = `/workflows/{workflowId}/steps/{stepId}/approve`
                .replace(`{${"workflowId"}}`, encodeURIComponent(String(workflowId)))
                .replace(`{${"stepId"}}`, encodeURIComponent(String(stepId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(workflowDecisionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cancel workflow
         * @param {string} workflowId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelWorkflow: async (workflowId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workflowId' is not null or undefined
            assertParamExists('cancelWorkflow', 'workflowId', workflowId)
            const localVarPath = `/workflows/{workflowId}/cancel`
                .replace(`{${"workflowId"}}`, encodeURIComponent(String(workflowId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Assign approval workflow to a document
         * @param {CreateWorkflowRequest} createWorkflowRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWorkflow: async (createWorkflowRequest: CreateWorkflowRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createWorkflowRequest' is not null or undefined
            assertParamExists('createWorkflow', 'createWorkflowRequest', createWorkflowRequest)
            const localVarPath = `/workflows`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createWorkflowRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create workflow template
         * @param {CreateWorkflowTemplateRequest} createWorkflowTemplateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWorkflowTemplate: async (createWorkflowTemplateRequest: CreateWorkflowTemplateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createWorkflowTemplateRequest' is not null or undefined
            assertParamExists('createWorkflowTemplate', 'createWorkflowTemplateRequest', createWorkflowTemplateRequest)
            const localVarPath = `/workflow-templates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createWorkflowTemplateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete workflow template
         * @param {string} templateId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWorkflowTemplate: async (templateId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'templateId' is not null or undefined
            assertParamExists('deleteWorkflowTemplate', 'templateId', templateId)
            const localVarPath = `/workflow-templates/{templateId}`
                .replace(`{${"templateId"}}`, encodeURIComponent(String(templateId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get workflow instance
         * @param {string} workflowId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkflow: async (workflowId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workflowId' is not null or undefined
            assertParamExists('getWorkflow', 'workflowId', workflowId)
            const localVarPath = `/workflows/{workflowId}`
                .replace(`{${"workflowId"}}`, encodeURIComponent(String(workflowId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get workflow history
         * @param {string} workflowId 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkflowHistory: async (workflowId: string, page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workflowId' is not null or undefined
            assertParamExists('getWorkflowHistory', 'workflowId', workflowId)
            const localVarPath = `/workflows/{workflowId}/history`
                .replace(`{${"workflowId"}}`, encodeURIComponent(String(workflowId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get workflow template
         * @param {string} templateId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkflowTemplate: async (templateId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'templateId' is not null or undefined
            assertParamExists('getWorkflowTemplate', 'templateId', templateId)
            const localVarPath = `/workflow-templates/{templateId}`
                .replace(`{${"templateId"}}`, encodeURIComponent(String(templateId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List workflow templates
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listWorkflowTemplates: async (page?: number, size?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/workflow-templates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List workflow instances
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort expression: field,asc or field,desc
         * @param {ListWorkflowsStatusEnum} [status] 
         * @param {string} [fileId] 
         * @param {string} [assigneeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listWorkflows: async (page?: number, size?: number, sort?: string, status?: ListWorkflowsStatusEnum, fileId?: string, assigneeId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/workflows`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (fileId !== undefined) {
                localVarQueryParameter['fileId'] = fileId;
            }

            if (assigneeId !== undefined) {
                localVarQueryParameter['assigneeId'] = assigneeId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reject workflow step
         * @param {string} workflowId 
         * @param {string} stepId 
         * @param {WorkflowDecisionRequest} [workflowDecisionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectStep: async (workflowId: string, stepId: string, workflowDecisionRequest?: WorkflowDecisionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workflowId' is not null or undefined
            assertParamExists('rejectStep', 'workflowId', workflowId)
            // verify required parameter 'stepId' is not null or undefined
            assertParamExists('rejectStep', 'stepId', stepId)
            const localVarPath = `/workflows/{workflowId}/steps/{stepId}/reject`
                .replace(`{${"workflowId"}}`, encodeURIComponent(String(workflowId)))
                .replace(`{${"stepId"}}`, encodeURIComponent(String(stepId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(workflowDecisionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Submit document for approval
         * @param {string} workflowId 
         * @param {WorkflowSubmitRequest} [workflowSubmitRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitWorkflow: async (workflowId: string, workflowSubmitRequest?: WorkflowSubmitRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workflowId' is not null or undefined
            assertParamExists('submitWorkflow', 'workflowId', workflowId)
            const localVarPath = `/workflows/{workflowId}/submit`
                .replace(`{${"workflowId"}}`, encodeURIComponent(String(workflowId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(workflowSubmitRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update workflow template
         * @param {string} templateId 
         * @param {CreateWorkflowTemplateRequest} createWorkflowTemplateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWorkflowTemplate: async (templateId: string, createWorkflowTemplateRequest: CreateWorkflowTemplateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'templateId' is not null or undefined
            assertParamExists('updateWorkflowTemplate', 'templateId', templateId)
            // verify required parameter 'createWorkflowTemplateRequest' is not null or undefined
            assertParamExists('updateWorkflowTemplate', 'createWorkflowTemplateRequest', createWorkflowTemplateRequest)
            const localVarPath = `/workflow-templates/{templateId}`
                .replace(`{${"templateId"}}`, encodeURIComponent(String(templateId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createWorkflowTemplateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WorkflowsApi - functional programming interface
 */
export const WorkflowsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WorkflowsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Approve workflow step
         * @param {string} workflowId 
         * @param {string} stepId 
         * @param {WorkflowDecisionRequest} [workflowDecisionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approveStep(workflowId: string, stepId: string, workflowDecisionRequest?: WorkflowDecisionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowInstanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approveStep(workflowId, stepId, workflowDecisionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.approveStep']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cancel workflow
         * @param {string} workflowId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelWorkflow(workflowId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowInstanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelWorkflow(workflowId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.cancelWorkflow']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Assign approval workflow to a document
         * @param {CreateWorkflowRequest} createWorkflowRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createWorkflow(createWorkflowRequest: CreateWorkflowRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowInstanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createWorkflow(createWorkflowRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.createWorkflow']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create workflow template
         * @param {CreateWorkflowTemplateRequest} createWorkflowTemplateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createWorkflowTemplate(createWorkflowTemplateRequest: CreateWorkflowTemplateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowTemplateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createWorkflowTemplate(createWorkflowTemplateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.createWorkflowTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete workflow template
         * @param {string} templateId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteWorkflowTemplate(templateId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteWorkflowTemplate(templateId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.deleteWorkflowTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get workflow instance
         * @param {string} workflowId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWorkflow(workflowId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowInstanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWorkflow(workflowId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.getWorkflow']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get workflow history
         * @param {string} workflowId 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWorkflowHistory(workflowId: string, page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowHistoryPageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWorkflowHistory(workflowId, page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.getWorkflowHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get workflow template
         * @param {string} templateId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWorkflowTemplate(templateId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowTemplateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWorkflowTemplate(templateId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.getWorkflowTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List workflow templates
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listWorkflowTemplates(page?: number, size?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowTemplatePageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listWorkflowTemplates(page, size, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.listWorkflowTemplates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List workflow instances
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort expression: field,asc or field,desc
         * @param {ListWorkflowsStatusEnum} [status] 
         * @param {string} [fileId] 
         * @param {string} [assigneeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listWorkflows(page?: number, size?: number, sort?: string, status?: ListWorkflowsStatusEnum, fileId?: string, assigneeId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowInstancePageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listWorkflows(page, size, sort, status, fileId, assigneeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.listWorkflows']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Reject workflow step
         * @param {string} workflowId 
         * @param {string} stepId 
         * @param {WorkflowDecisionRequest} [workflowDecisionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rejectStep(workflowId: string, stepId: string, workflowDecisionRequest?: WorkflowDecisionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowInstanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rejectStep(workflowId, stepId, workflowDecisionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.rejectStep']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Submit document for approval
         * @param {string} workflowId 
         * @param {WorkflowSubmitRequest} [workflowSubmitRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitWorkflow(workflowId: string, workflowSubmitRequest?: WorkflowSubmitRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowInstanceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitWorkflow(workflowId, workflowSubmitRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.submitWorkflow']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update workflow template
         * @param {string} templateId 
         * @param {CreateWorkflowTemplateRequest} createWorkflowTemplateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateWorkflowTemplate(templateId: string, createWorkflowTemplateRequest: CreateWorkflowTemplateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkflowTemplateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateWorkflowTemplate(templateId, createWorkflowTemplateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkflowsApi.updateWorkflowTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WorkflowsApi - factory interface
 */
export const WorkflowsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WorkflowsApiFp(configuration)
    return {
        /**
         * 
         * @summary Approve workflow step
         * @param {string} workflowId 
         * @param {string} stepId 
         * @param {WorkflowDecisionRequest} [workflowDecisionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveStep(workflowId: string, stepId: string, workflowDecisionRequest?: WorkflowDecisionRequest, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowInstanceResponse> {
            return localVarFp.approveStep(workflowId, stepId, workflowDecisionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cancel workflow
         * @param {string} workflowId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelWorkflow(workflowId: string, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowInstanceResponse> {
            return localVarFp.cancelWorkflow(workflowId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Assign approval workflow to a document
         * @param {CreateWorkflowRequest} createWorkflowRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWorkflow(createWorkflowRequest: CreateWorkflowRequest, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowInstanceResponse> {
            return localVarFp.createWorkflow(createWorkflowRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create workflow template
         * @param {CreateWorkflowTemplateRequest} createWorkflowTemplateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWorkflowTemplate(createWorkflowTemplateRequest: CreateWorkflowTemplateRequest, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowTemplateResponse> {
            return localVarFp.createWorkflowTemplate(createWorkflowTemplateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete workflow template
         * @param {string} templateId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWorkflowTemplate(templateId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteWorkflowTemplate(templateId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get workflow instance
         * @param {string} workflowId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkflow(workflowId: string, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowInstanceResponse> {
            return localVarFp.getWorkflow(workflowId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get workflow history
         * @param {string} workflowId 
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkflowHistory(workflowId: string, page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowHistoryPageResponse> {
            return localVarFp.getWorkflowHistory(workflowId, page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get workflow template
         * @param {string} templateId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkflowTemplate(templateId: string, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowTemplateResponse> {
            return localVarFp.getWorkflowTemplate(templateId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List workflow templates
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listWorkflowTemplates(page?: number, size?: number, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowTemplatePageResponse> {
            return localVarFp.listWorkflowTemplates(page, size, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List workflow instances
         * @param {number} [page] Zero-based page index
         * @param {number} [size] Number of items per page
         * @param {string} [sort] Sort expression: field,asc or field,desc
         * @param {ListWorkflowsStatusEnum} [status] 
         * @param {string} [fileId] 
         * @param {string} [assigneeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listWorkflows(page?: number, size?: number, sort?: string, status?: ListWorkflowsStatusEnum, fileId?: string, assigneeId?: string, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowInstancePageResponse> {
            return localVarFp.listWorkflows(page, size, sort, status, fileId, assigneeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Reject workflow step
         * @param {string} workflowId 
         * @param {string} stepId 
         * @param {WorkflowDecisionRequest} [workflowDecisionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectStep(workflowId: string, stepId: string, workflowDecisionRequest?: WorkflowDecisionRequest, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowInstanceResponse> {
            return localVarFp.rejectStep(workflowId, stepId, workflowDecisionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Submit document for approval
         * @param {string} workflowId 
         * @param {WorkflowSubmitRequest} [workflowSubmitRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitWorkflow(workflowId: string, workflowSubmitRequest?: WorkflowSubmitRequest, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowInstanceResponse> {
            return localVarFp.submitWorkflow(workflowId, workflowSubmitRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update workflow template
         * @param {string} templateId 
         * @param {CreateWorkflowTemplateRequest} createWorkflowTemplateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWorkflowTemplate(templateId: string, createWorkflowTemplateRequest: CreateWorkflowTemplateRequest, options?: RawAxiosRequestConfig): AxiosPromise<WorkflowTemplateResponse> {
            return localVarFp.updateWorkflowTemplate(templateId, createWorkflowTemplateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WorkflowsApi - object-oriented interface
 */
export class WorkflowsApi extends BaseAPI {
    /**
     * 
     * @summary Approve workflow step
     * @param {string} workflowId 
     * @param {string} stepId 
     * @param {WorkflowDecisionRequest} [workflowDecisionRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public approveStep(workflowId: string, stepId: string, workflowDecisionRequest?: WorkflowDecisionRequest, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).approveStep(workflowId, stepId, workflowDecisionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cancel workflow
     * @param {string} workflowId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cancelWorkflow(workflowId: string, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).cancelWorkflow(workflowId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Assign approval workflow to a document
     * @param {CreateWorkflowRequest} createWorkflowRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createWorkflow(createWorkflowRequest: CreateWorkflowRequest, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).createWorkflow(createWorkflowRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create workflow template
     * @param {CreateWorkflowTemplateRequest} createWorkflowTemplateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createWorkflowTemplate(createWorkflowTemplateRequest: CreateWorkflowTemplateRequest, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).createWorkflowTemplate(createWorkflowTemplateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete workflow template
     * @param {string} templateId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteWorkflowTemplate(templateId: string, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).deleteWorkflowTemplate(templateId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get workflow instance
     * @param {string} workflowId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getWorkflow(workflowId: string, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).getWorkflow(workflowId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get workflow history
     * @param {string} workflowId 
     * @param {number} [page] Zero-based page index
     * @param {number} [size] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getWorkflowHistory(workflowId: string, page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).getWorkflowHistory(workflowId, page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get workflow template
     * @param {string} templateId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getWorkflowTemplate(templateId: string, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).getWorkflowTemplate(templateId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List workflow templates
     * @param {number} [page] Zero-based page index
     * @param {number} [size] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listWorkflowTemplates(page?: number, size?: number, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).listWorkflowTemplates(page, size, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List workflow instances
     * @param {number} [page] Zero-based page index
     * @param {number} [size] Number of items per page
     * @param {string} [sort] Sort expression: field,asc or field,desc
     * @param {ListWorkflowsStatusEnum} [status] 
     * @param {string} [fileId] 
     * @param {string} [assigneeId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listWorkflows(page?: number, size?: number, sort?: string, status?: ListWorkflowsStatusEnum, fileId?: string, assigneeId?: string, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).listWorkflows(page, size, sort, status, fileId, assigneeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Reject workflow step
     * @param {string} workflowId 
     * @param {string} stepId 
     * @param {WorkflowDecisionRequest} [workflowDecisionRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public rejectStep(workflowId: string, stepId: string, workflowDecisionRequest?: WorkflowDecisionRequest, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).rejectStep(workflowId, stepId, workflowDecisionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Submit document for approval
     * @param {string} workflowId 
     * @param {WorkflowSubmitRequest} [workflowSubmitRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public submitWorkflow(workflowId: string, workflowSubmitRequest?: WorkflowSubmitRequest, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).submitWorkflow(workflowId, workflowSubmitRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update workflow template
     * @param {string} templateId 
     * @param {CreateWorkflowTemplateRequest} createWorkflowTemplateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateWorkflowTemplate(templateId: string, createWorkflowTemplateRequest: CreateWorkflowTemplateRequest, options?: RawAxiosRequestConfig) {
        return WorkflowsApiFp(this.configuration).updateWorkflowTemplate(templateId, createWorkflowTemplateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ListWorkflowsStatusEnum = {
    Pending: 'pending',
    InProgress: 'in_progress',
    Approved: 'approved',
    Rejected: 'rejected',
    Cancelled: 'cancelled'
} as const;
export type ListWorkflowsStatusEnum = typeof ListWorkflowsStatusEnum[keyof typeof ListWorkflowsStatusEnum];
