/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Document Management System API
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@dms.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserSummary } from './user-summary';

export interface AuditLogEntry {
    'id'?: string;
    'action'?: string;
    'actor'?: UserSummary;
    'resourceType'?: AuditLogEntryResourceTypeEnum;
    'resourceId'?: string | null;
    'resourceName'?: string | null;
    'ipAddress'?: string;
    'userAgent'?: string | null;
    /**
     * Additional context specific to the action
     */
    'metadata'?: { [key: string]: any; };
    'occurredAt'?: string;
}

export const AuditLogEntryResourceTypeEnum = {
    File: 'file',
    Folder: 'folder',
    User: 'user',
    Team: 'team',
    Workflow: 'workflow',
    Share: 'share',
    Auth: 'auth',
    System: 'system'
} as const;

export type AuditLogEntryResourceTypeEnum = typeof AuditLogEntryResourceTypeEnum[keyof typeof AuditLogEntryResourceTypeEnum];


