/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Document Management System API
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@dms.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface NotificationResponse {
    'id'?: string;
    'type'?: NotificationResponseTypeEnum;
    'title'?: string;
    'body'?: string;
    'read'?: boolean;
    'resourceType'?: string | null;
    'resourceId'?: string | null;
    'actionUrl'?: string | null;
    'createdAt'?: string;
}

export const NotificationResponseTypeEnum = {
    Share: 'share',
    WorkflowAssigned: 'workflow_assigned',
    WorkflowApproved: 'workflow_approved',
    WorkflowRejected: 'workflow_rejected',
    Mention: 'mention',
    System: 'system'
} as const;

export type NotificationResponseTypeEnum = typeof NotificationResponseTypeEnum[keyof typeof NotificationResponseTypeEnum];


