/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Document Management System API
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@dms.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PublicLinkRequest {
    'resourceType': PublicLinkRequestResourceTypeEnum;
    'resourceId': string;
    'permission'?: PublicLinkRequestPermissionEnum;
    /**
     * Expiry time; null for no expiry
     */
    'expiresAt'?: string | null;
    /**
     * Optional link password
     */
    'password'?: string;
    /**
     * Maximum number of uses; null for unlimited
     */
    'maxDownloads'?: number | null;
}

export const PublicLinkRequestResourceTypeEnum = {
    File: 'file',
    Folder: 'folder'
} as const;

export type PublicLinkRequestResourceTypeEnum = typeof PublicLinkRequestResourceTypeEnum[keyof typeof PublicLinkRequestResourceTypeEnum];
export const PublicLinkRequestPermissionEnum = {
    Read: 'read',
    Write: 'write'
} as const;

export type PublicLinkRequestPermissionEnum = typeof PublicLinkRequestPermissionEnum[keyof typeof PublicLinkRequestPermissionEnum];


