/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Document Management System API
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@dms.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface TenantResponse {
    'id'?: string;
    'name'?: string;
    /**
     * URL-safe identifier
     */
    'slug'?: string;
    'logoUrl'?: string | null;
    'primaryColor'?: string | null;
    'defaultUserRole'?: TenantResponseDefaultUserRoleEnum;
    'ssoEnabled'?: boolean;
    'ssoProvider'?: string | null;
    'mfaRequired'?: boolean;
    'status'?: TenantResponseStatusEnum;
    'createdAt'?: string;
    'updatedAt'?: string;
}

export const TenantResponseDefaultUserRoleEnum = {
    Admin: 'admin',
    Manager: 'manager',
    Editor: 'editor',
    Viewer: 'viewer'
} as const;

export type TenantResponseDefaultUserRoleEnum = typeof TenantResponseDefaultUserRoleEnum[keyof typeof TenantResponseDefaultUserRoleEnum];
export const TenantResponseStatusEnum = {
    Active: 'active',
    Suspended: 'suspended',
    Trialing: 'trialing'
} as const;

export type TenantResponseStatusEnum = typeof TenantResponseStatusEnum[keyof typeof TenantResponseStatusEnum];


