/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Document Management System API
 * A production-ready, multi-tenant SaaS Document Management System API with role-based access control, document workflows, file versioning, sharing, audit logs, and analytics.  ## Authentication All endpoints (except login, register-invite) require a valid JWT Bearer token.  ## Multi-Tenancy Every request is scoped to a tenant via the `X-Tenant-ID` header or resolved from the JWT claims.  ## Pagination List endpoints support `page` (0-indexed), `size`, and `sort` query parameters.  ## Error Responses All error responses follow the `ErrorResponse` schema with `code`, `message`, and optional `details`. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-support@dms.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration.ts';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "/v1".replace(/\/+$/, "");

export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

export interface RequestArgs {
    url: string;
    options: RawAxiosRequestConfig;
}

export class BaseAPI {
    protected configuration: Configuration | undefined;
    protected basePath: string;
    protected axios: AxiosInstance;

    constructor(configuration?: Configuration, basePath: string = BASE_PATH, axios: AxiosInstance = globalAxios) {
        this.basePath = basePath;
        this.axios = axios;
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath ?? basePath;
        }
    }
}

export class RequiredError extends Error {
    public field: string;

    constructor(field: string, msg?: string) {
        super(msg);
        this.field = field;
        this.name = "RequiredError"
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

export const operationServerMap: ServerMap = {
}
